# to build image:
# > docker-compose build

# to run container (and keep atached to the container)
# > docker-compose up [<service_name>]

# to run container as a daemon
# > docker-compose up -d [<service_name>]
# to attach to daemon container
# > docker exec -it <container_id> bash

# to stop the started container
# > docker-compose stop [<service_name>]

# to stop and remove the started container
# > docker-compose down [<service_name>]

version: "3"
services:
  asdt_api_2_0:
    image: asdt_api:3.0
    restart: always
    tty: true
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - $API_PORT:8080
    environment:
      - MONGO_HOST=$MONGO_HOST
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    logging:
     driver: "syslog"
     options:
       tag: "asdt"
  mongo_express_2_0:
    image: mongo-express:0.49
    restart: always
    volumes:
      - /home/vagrant/mongodocker/:/data/db/
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: $ME_USERNAME
      ME_CONFIG_BASICAUTH_PASSWORD: $ME_PASSWORD
      ME_CONFIG_MONGODB_SERVER: $MONGO_HOST
      ME_CONFIG_MONGODB_PORT: $MONGO_PORT
      ME_CONFIG_SITE_BASEURL: '/me/'
    ports:
        - $ME_PORT:8081
    logging:
     driver: "syslog"
     options:
       tag: "asdt"

  # asdt_mongo:
  #   image: mongo:3.4-xenial
  #   restart: always
  #   volumes:
  #     - /home/vagrant/mongodocker/:/data/db/
  #   environment:
  #     MONGO_INITDB_DATABASE: asdt
  #   ports:
  #       - 27017:27017
  #   # logging:
  #   #  driver: "syslog"
  #   #  options:
  #   #    tag: "asdt"

